### ISSUE TITLE
Trouble with csso

### ISSUE THREAD

**Issue by neonick** [lahmatiy/postcss-csso#4]
I use it in the bottom of postcss plugins, but after run build task I see this error 
![error](https://cloud.githubusercontent.com/assets/557977/14425928/55f02828-ffeb-11e5-826b-3e78acff2012.PNG)

I'm not a good developer, but can you tell what the problem might be?

**Comment by lahmatiy** [comment]
Looks like non-string was passed to CSSO parser. I'm not sure where it's happen since no line on screenshot.

![image](https://cloud.githubusercontent.com/assets/270491/14444155/98550876-004c-11e6-8cf8-f10ad0bb5ef1.png)

Also try add to `parseToCsso` function in `lib/postcssToCsso.js` statement:

```js
if (!str) {
    console.log('Problem node:', node.toString(), node);
}
```

So function should looks like:

```js
function parseToCsso(str, context, node) {
    if (!str) {
        console.log('Problem node:', node.toString(), node);
    }

    var cssoNode = parse(str, {
        context: context
    });

    cssoNode.info = getInfo(node);

    return cssoNode;
}
```

It should output a problem node. This output might to be useful to solve the issue.

**Comment by neonick** [comment]
I figured out that it breaks my assembly — the CSSO incorrectly handles with normalize.css@4.0.0. 
I tried to run it in an empty assembly, where there is only non-minificated normalize — the same error.

**Comment by lahmatiy** [comment]
I tried process normalize 4.0.0 – no problem with it. Maybe you can provide a problem file?

**Comment by neonick** [comment]
I found. I start deleting some postcss-plugins and when I delete postcss-font-magician — all was well.

**Comment by lahmatiy** [comment]
`1.1.1` is out with this issue fix.
Thank you!

**Comment by neonick** [comment]
Great! Thank you!
